backend:
  name: github
  repo: dheerajvs/kitchen # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "public/img" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "recipe" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Recipe" # Used in the UI, ie.: "New Post"
    folder: "html/data/_recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "datePublished", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Time (hours)", name: "totalTimeHours", widget: "number"}
      - {label: "Time (minutes)", name: "totalTimeMinutes", widget: "number"}
      - {label: "Yield", name: "recipeYield", widget: "string"}
      - {label: "Ingredients", name: "recipeIngredient", widget: "markdown"}
      - {label: "Procedure", name: "recipeInstructions", widget: "markdown"}
